<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\core\Mvf.Graph\Mvf.Graph.csproj" />
    <ProjectReference Include="..\..\src\core\Mvf.Abstractions\Mvf.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\engine\Mvf.Engine\Mvf.Engine.csproj" />
    <ProjectReference Include="..\..\src\hosting\Mvf.Hosting.Worker\Mvf.Hosting.Worker.csproj" />
    <ProjectReference Include="..\..\src\transports\Mvf.Transport.SharedMemory\Mvf.Transport.SharedMemory.csproj" />
    <ProjectReference Include="..\..\src\sdk\dotnet\Mvf.Sdk\Mvf.Sdk.csproj" />
  </ItemGroup>

</Project>
